### ISSUE TITLE
Missing 'download ' in menu

### ISSUE THREAD

**Issue by ludoo0d0a** [c9/core#46]
My cloud9 ide has no "Download" item in my contextual menu.
Are there any conditions to display it ?

**Comment by nightwing** [comment]
Should be fixed by https://github.com/c9/core/commit/a822db752f0bbb0113bb0b8eb314fced2283b330. Thanks for reporting the bug.

**Comment by ludoo0d0a** [comment]
I updated with ./scripts/install-sdk.sh, then restart, but menu item is still missing.
anyway, file plugins/c9.ide.download/download.js is present but seems not to be loaded.

**Comment by nightwing** [comment]
You are right, i forgot to add it to the config, should be fixed by https://github.com/c9/core/commit/0a6a7aa3131794724f87357a1d566ec55b4eb2d7

**Comment by ludoo0d0a** [comment]
I confirm. It works now. Thanks !
